#!/usr/bin/env python3
"""Regenerate .env.staging.

Staging borrows three things from production (.env) — the OpenRouter key, the
sandbox settings, and the model default — because a walkthrough against a fake
detection engine tells you nothing. Everything else is staging's own: its own
database, its own Redis logical DB, its own master key, and Stripe test mode.

Stripe credentials come from the CLI login (~/.config/stripe/config.toml) and
expire roughly 90 days after `stripe login`. Re-run this script after logging
in again. Run it from the repo root:

    python3 scripts/staging-env.py
"""
from __future__ import annotations

import pathlib
import secrets
import sys
import tomllib

REPO = pathlib.Path(__file__).resolve().parent.parent

# Test-mode prices mirroring production amounts: Solo $12, Pro $49, Team $199.
TEST_PRICES = {
    "STRIPE_SOLO_PRICE_ID": "price_1U3QDc8LghiREdMSVQxja1pI",
    "STRIPE_PRO_PRICE_ID": "price_1U2NQY8LghiREdMSeqNUIViy",
    "STRIPE_TEAM_PRICE_ID": "price_1U2NQZ8LghiREdMSZL8Hgbyy",
}
# Exists in test mode but left unset below, mirroring production.
TEST_COMPLIANCE_PRICE = "price_1U2NQa8LghiREdMShwMMHOD8"

INHERITED = ["OPENROUTER_API_KEY", "SANDBOX_URL", "SANDBOX_HMAC_SECRET",
             "DEFAULT_MODEL", "X402_ENABLED", "ALLOW_UNISOLATED_EXECUTION",
             "STRIPE_ACCOUNT_ID"]


def read_env(path: pathlib.Path) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, value = line.split("=", 1)
            out[key.strip()] = value.strip()
    return out


def main() -> int:
    prod_path = REPO / ".env"
    if not prod_path.exists():
        print("no .env to inherit from", file=sys.stderr)
        return 1
    prod = read_env(prod_path)

    cfg_path = pathlib.Path.home() / ".config/stripe/config.toml"
    if not cfg_path.exists():
        print("Stripe CLI not logged in — run `stripe login`", file=sys.stderr)
        return 1
    cfg = tomllib.loads(cfg_path.read_text())["default"]

    secret = cfg.get("test_mode_api_key", "")
    if not secret.startswith("sk_test"):
        print(f"expected a test-mode key, got {secret[:8]!r}", file=sys.stderr)
        return 1

    # Preserve the webhook secret across regenerations; it is stable per login.
    webhook = ""
    existing = REPO / ".env.staging"
    if existing.exists():
        webhook = read_env(existing).get("STRIPE_WEBHOOK_SECRET", "")

    body = f"""# Parse staging — Stripe TEST MODE. Never point this at production data.
# Generated by scripts/staging-env.py; started by scripts/staging-up.sh.
NODE_ENV=production
PORT=3005
PUBLIC_BASE_URL=http://localhost:3005

# Isolated staging stores: own database, own Redis logical DB (3).
DATABASE_URL=postgresql://kublai@localhost:15432/parse_staging
REDIS_URL=redis://localhost:6379/3

# ── Stripe TEST MODE ──
# From the Stripe CLI login; expires ~90 days after `stripe login`. If checkout
# starts returning 401, log in again and re-run scripts/staging-env.py.
STRIPE_SECRET_KEY={secret}
STRIPE_PUBLISHABLE_KEY={cfg.get('test_mode_pub_key', '')}
STRIPE_ACCOUNT_ID={prod.get('STRIPE_ACCOUNT_ID', '')}
{chr(10).join(f'{k}={v}' for k, v in TEST_PRICES.items())}
# Deliberately unset, exactly as in production, so an agent that tries to buy
# Compliance meets the same 503 the live site gives. The test-mode price
# ({TEST_COMPLIANCE_PRICE}) exists if a run needs to enable it.
# STRIPE_COMPLIANCE_PRICE_ID=
# Stable per CLI login: `stripe listen --print-secret`.
STRIPE_WEBHOOK_SECRET={webhook}

# Staging-only credentials. Not the production keys.
MASTER_API_KEY=pfa_staging_{secrets.token_hex(16)}
DEMO_API_KEY=pfa_staging_demo_{secrets.token_hex(8)}

KEY_GENERATION_ENABLED=true
ALLOWED_ORIGINS=http://localhost:3005
X402_ENABLED={prod.get('X402_ENABLED', 'false')}
ALLOW_UNISOLATED_EXECUTION={prod.get('ALLOW_UNISOLATED_EXECUTION', 'false')}
DEFAULT_MODEL={prod.get('DEFAULT_MODEL', '')}

# Shared with production on purpose: the semantic layer has to be real for a
# walkthrough to mean anything. Staging usage bills the same OpenRouter account.
OPENROUTER_API_KEY={prod.get('OPENROUTER_API_KEY', '')}
SANDBOX_URL={prod.get('SANDBOX_URL', '')}
SANDBOX_HMAC_SECRET={prod.get('SANDBOX_HMAC_SECRET', '')}

# RESEND_API_KEY is intentionally absent: staging must not send real email.
# Stripe's own test-mode receipts still arrive.
"""
    target = REPO / ".env.staging"
    target.write_text(body)
    target.chmod(0o600)
    print(f"wrote {target}")
    if not webhook:
        print("STRIPE_WEBHOOK_SECRET is empty — fill it from `stripe listen --print-secret`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
